/* Generated by cbindgen - do not edit manually */

#ifndef TANTIVY_FTS_H
#define TANTIVY_FTS_H

/* Warning: this file is autogenerated by cbindgen. Do not modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Reserved field name for Rag3db node IDs (auto-added to every schema).
 * u64, FAST | INDEXED. Used by tantivy_search_filtered().
 */
#define TANTIVY_NODE_ID_FIELD "_node_id"

/**
 * Suffix for raw (non-stemmed) counterpart fields.
 * When a stemmer is active, each text field "foo" also has "foo._raw".
 */
#define TANTIVY_RAW_SUFFIX "._raw"

/**
 * Opaque handle exposed through the C FFI.
 */
typedef struct TantivyHandle TantivyHandle;

/**
 * Opaque handle type for the C API.
 */
typedef struct TantivyHandle *TantivyHandlePtr;

/**
 * Create a new Tantivy index at the given path.
 *
 * `path`: filesystem path for the index directory.
 * `schema_json`: JSON string defining the schema (see query::SchemaConfig).
 *
 * Returns an opaque handle, or null on error.
 */
TantivyHandlePtr tantivy_create_index(const char *path, const char *schema_json);

/**
 * Open an existing Tantivy index at the given path.
 *
 * Returns an opaque handle, or null on error.
 */
TantivyHandlePtr tantivy_open_index(const char *path);

/**
 * Close an index and free its resources.
 */
void tantivy_close_index(TantivyHandlePtr handle);

/**
 * Add a document to the index. The document is a JSON object whose keys
 * correspond to field names in the schema.
 *
 * Returns the opstamp (monotonic operation id), or -1 on error.
 */
int64_t tantivy_add_document(TantivyHandlePtr handle, const char *doc_json);

/**
 * Delete documents matching a term (field=value).
 *
 * Deletions take effect on the next commit.
 * Returns the opstamp, or -1 on error.
 */
int64_t tantivy_delete_by_term(TantivyHandlePtr handle, const char *field_name, const char *value);

/**
 * Commit pending operations (adds and deletes).
 *
 * Creates a new segment for added documents. Returns the opstamp, or -1 on error.
 */
int64_t tantivy_commit(TantivyHandlePtr handle);

/**
 * Rollback pending operations.
 */
void tantivy_rollback(TantivyHandlePtr handle);

/**
 * Search the index.
 *
 * `query_json`: JSON query (see query::QueryConfig for format).
 * `limit`: maximum number of results.
 *
 * Returns a JSON string: [{"score": 1.23, "doc": {...}}, ...].
 * Caller must free the returned string with tantivy_free_string.
 * Returns an error JSON on failure.
 */
char *tantivy_search(TantivyHandlePtr handle, const char *query_json, uint32_t limit);

/**
 * Search the index with pre-filtering by allowed node IDs.
 *
 * Only documents whose `_node_id` value is in the `allowed_ids` array are considered.
 * This is the key function for Rag3db graph-filtered FTS:
 *   1. C++ extension runs Cypher WHERE → gets matching node IDs
 *   2. Passes them here → Tantivy only scores those documents
 *
 * `allowed_ids`: pointer to a u64 array of allowed node IDs.
 * `num_ids`: number of elements in the array.
 *
 * Returns a JSON string like tantivy_search. Caller must free with tantivy_free_string.
 */
char *tantivy_search_filtered(TantivyHandlePtr handle,
                              const char *query_json,
                              uint32_t limit,
                              const uint64_t *allowed_ids,
                              uint32_t num_ids);

/**
 * Reload the reader to see the latest committed segments.
 *
 * Call this after tantivy_commit to make new documents visible to search.
 */
void tantivy_reload_reader(TantivyHandlePtr handle);

/**
 * Get the index schema as a JSON string.
 *
 * Caller must free the returned string with tantivy_free_string.
 */
char *tantivy_get_schema(TantivyHandlePtr handle);

/**
 * Get the number of documents in the index (including deleted but not yet merged).
 */
uint64_t tantivy_num_docs(TantivyHandlePtr handle);

/**
 * Free a string returned by any tantivy_* function.
 */
void tantivy_free_string(char *ptr);

#endif  /* TANTIVY_FTS_H */
